### ISSUE TITLE
Problema con el Push

### ISSUE THREAD

**Issue by acadetev** [maestria-geotel-201902/unidad-0-asignacion-1-asig-conrstudio-issues-acadetev#1]
Me esta saliendo en siguiente error
>>> git push origin refs/heads/master
Everything up-to-date

Method not found

**Comment by geofis** [comment]
Supongo que este *issue* pudo ser real en algún momento, pero igualmente imagino que ya está resuelto. ¿Puedo cerrarlo? Creo que también puedes cerrarlo tú.
